### PR TITLE
Add macOS x86_64 wheels to cover Python 3.7 on Intel Macs

### PR DESCRIPTION
**Pull request by ulupo**

### CODE REVIEW

**Comment by ulupo** [comment]
@MonkeyBreaker I've checked and this achieves the desired effect.  I have also included the x86_64 macOS wheels in the 0.2.2 release.

**Comment by MonkeyBreaker** [comment]
@ulupo nice catch, sorry missed the 3.7 wheels on Mac, even if I told you I saw them ...
This should also be forwarded to pyflagser before merge of the latest PR about github actions

**Comment by ulupo** [comment]
Ok great!  Should we merge this now and then proceed with `pyflagser`?

**Comment by MonkeyBreaker** [comment]
> Ok great! Should we merge this now and then proceed with pyflagser?

Yes, definitely ! You can forward the change, otherwise I do it this evening.

**Pull request merged**
