### PR TITLE
Improve Notes section in ripser_parallel

### LINKED ISSUE #35: Improve docstrings
There are some leftover inaccuracies in the docs for `ripser_parallel` especially when we mention the relationship with Ripser/ripser and scikit-tda/ripser.py.

### PR DESCRIPTION
**Pull request by ulupo**
Describe the relationship with other projects more comprehensively and accurately. Fixes #35.

### CODE REVIEW

**Comment by ulupo** [comment]
@MonkeyBreaker ready to review!

**Comment by MonkeyBreaker** [comment]
If we are improving the documentation, could we remove the Brackets around  `Returns` section ?
Because looking at the output produced, I do not find them useful:
https://giotto-ai.github.io/giotto-ph/build/html/modules/ripser_parallel.html

**Comment by ulupo** [comment]
@MonkeyBreaker how about now?

**Comment by MonkeyBreaker** [comment]
> @MonkeyBreaker how about now?

Much better, thank you !

**Comment by MonkeyBreaker** [comment]
Otherwise the rest LGTM !

**Comment by ulupo** [comment]
@MonkeyBreaker thanks!

**Pull request merged**
